required_version: ">=0.0.0"

x-metric-template: &metric-template
  type: host
  service_name: prod
  roles:
    - ALB
  host_name: {{ must_env `TARGET_ALB_NAME`}}
  aggregation_interval: 1m
  aggregation_method: max

metrics:
  - id: alb_p90_response_time
    name: custom.alb.response.time_p90
    <<: *metric-template

  - id: alb_p99_response_time
    name: custom.alb.response.time_p99
    <<: *metric-template

  - id: alb_5xx_count
    name: custom.alb.httpcode_count.target_5xx
    <<: *metric-template

  - id: alb_2xx_count
    name: custom.alb.httpcode_count.target_2xx
    <<: *metric-template

x-definition-template: &definition-template
  service_name:  {{ must_env `POST_METRIC_SERVICE`}}
  time_frame: 40320m #4weeks
  calculate_interval: 24h
  error_budget_size: 0.001

definitions:
  - id: availability
    objectives:
      - expr: rate(alb_2xx_count, alb_5xx_count + alb_2xx_count) >= 0.97
    <<: *definition-template

  - id: latency
    objectives:
      - expr: alb_p90_response_time <= 0.4
      - expr: alb_p99_response_time <= 0.85
    <<: *definition-template
